DESCRIBE TABLE STAGING.JOB_ADVERTISEMENTS;
DESCRIBE TABLE STAGING.JOB_ADVERTISEMENTS__MUST_HAVE__SKILLS;
SELECT * FROM STAGING.JOB_ADVERTISEMENTS__MUST_HAVE__SKILLS;


--tetsing linkage
SELECT * FROM STAGING.JOB_ADVERTISEMENTS
WHERE _dlt_id = 'tphWsKIkutC9Kg';