 USE ROLE SYSADMIN;

 SELECT CURRENT_ROLE();


 CREATE WAREHOUSE job_api_group_9
 WITH
 WAREHOUSE_SIZE ="XSMALL"
 AUTO_SUSPEND = 60
 AUTO_RESUME = TRUE
 INITIALLY_SUSPENDED = TRUE
COMMENT ="Warehouse for HR job analytics."; 


 CREATE DATABASE IF NOT EXISTS job_db;

 CREATE SCHEMA IF NOT EXISTS job_db.staging;


